// <auto-generated />
using System;
using GamePredictor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GamePredictor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260820101626_FixTimestampTypes")]
    partial class FixTimestampTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GamePredictor.Domain.Entities.Developers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AvgMetacriticLast3")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("Avg_Metacritic_Last_3");

                    b.Property<int>("GamesCount")
                        .HasColumnType("integer")
                        .HasColumnName("games_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("Developer_pkey");

                    b.ToTable("Developers", (string)null);
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<double?>("BudgetEstimate")
                        .HasPrecision(6, 2)
                        .HasColumnType("double precision")
                        .HasColumnName("budget_estimate");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("integer")
                        .HasColumnName("developer_id");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("genre");

                    b.Property<bool>("IsReleased")
                        .HasColumnType("boolean")
                        .HasColumnName("is_released");

                    b.Property<int?>("MetacriticScore")
                        .HasColumnType("integer")
                        .HasColumnName("metacritic_score");

                    b.Property<string>("Platforms")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("platforms");

                    b.Property<int?>("RawgId")
                        .HasColumnType("integer")
                        .HasColumnName("rawg_id");

                    b.Property<DateOnly?>("Releasedate")
                        .HasColumnType("date")
                        .HasColumnName("releasedate");

                    b.Property<int?>("SteamAppId")
                        .HasColumnType("integer")
                        .HasColumnName("steam_app_Id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("title");

                    b.Property<string>("TrailerYoutubeId")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("trailer_youtube_id");

                    b.HasKey("Id")
                        .HasName("Game_pkey");

                    b.HasIndex("DeveloperId");

                    b.ToTable("Game", (string)null);
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.NewsSentiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<string>("Keywords")
                        .HasColumnType("text")
                        .HasColumnName("keywords");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<decimal?>("Relevance")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("relevance");

                    b.Property<decimal?>("SentimentScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("sentiment_score");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("NewsSentiment_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("NewsSentiment", (string)null);
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.PreReleaseMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<int>("RedditMentions")
                        .HasColumnType("integer")
                        .HasColumnName("reddit_mentions");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("TwitchViewerAvg")
                        .HasColumnType("integer")
                        .HasColumnName("twitch_viewer_avg");

                    b.Property<int>("WishlistCount")
                        .HasColumnType("integer")
                        .HasColumnName("wishlist_count");

                    b.Property<long?>("YoutubeTrailerViews")
                        .HasColumnType("bigint")
                        .HasColumnName("youtube_trailer_views");

                    b.HasKey("Id")
                        .HasName("PreRelelaseMetric_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("PreReleaseMetrics", (string)null);
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Predictions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Arguments")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arguments");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("confidence");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("GameId")
                        .HasColumnType("integer")
                        .HasColumnName("game_id");

                    b.Property<decimal>("PredictedMetacritic")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("predicted_metacritic");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("risk_level");

                    b.Property<string>("SalesClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sales_class");

                    b.Property<bool?>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("Id")
                        .HasName("Prediction_pkey");

                    b.HasIndex("GameId");

                    b.ToTable("Predictions", (string)null);
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Game", b =>
                {
                    b.HasOne("GamePredictor.Domain.Entities.Developers", "Developer")
                        .WithMany("Games")
                        .HasForeignKey("DeveloperId")
                        .IsRequired()
                        .HasConstraintName("Game_developer_id_fkey");

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.NewsSentiment", b =>
                {
                    b.HasOne("GamePredictor.Domain.Entities.Game", "Game")
                        .WithMany("NewsSentiments")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("NewsSentiment_game_id_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.PreReleaseMetrics", b =>
                {
                    b.HasOne("GamePredictor.Domain.Entities.Game", "Game")
                        .WithMany("PreReleaseMetrics")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("PreRelelaseMetric_game_id_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Predictions", b =>
                {
                    b.HasOne("GamePredictor.Domain.Entities.Game", "Game")
                        .WithMany("Predictions")
                        .HasForeignKey("GameId")
                        .IsRequired()
                        .HasConstraintName("Prediction_game_id_fkey");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Developers", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GamePredictor.Domain.Entities.Game", b =>
                {
                    b.Navigation("NewsSentiments");

                    b.Navigation("PreReleaseMetrics");

                    b.Navigation("Predictions");
                });
#pragma warning restore 612, 618
        }
    }
}
