-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public."Developers"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "Avg_Metacritic_Last_3" numeric(4, 1) NOT NULL,
    games_count integer NOT NULL,
    CONSTRAINT "Developer_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Game"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    genre character varying(100) COLLATE pg_catalog."default" NOT NULL,
    releasedate date,
    platforms character varying(150) COLLATE pg_catalog."default",
    budget_estimate numeric(6, 2),
    metacritic_score integer,
    is_released boolean NOT NULL,
    "steam_app_Id" integer,
    trailer_youtube_id character varying(20) COLLATE pg_catalog."default",
    developer_id integer NOT NULL,
    rawg_id integer,
    CONSTRAINT "Game_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."NewsSentiment"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    source character varying(100) COLLATE pg_catalog."default" NOT NULL,
    published_at timestamp with time zone NOT NULL,
    sentiment_score numeric(3, 2),
    relevance numeric(3, 2),
    keywords text COLLATE pg_catalog."default",
    game_id integer NOT NULL,
    CONSTRAINT "NewsSentiment_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PreReleaseMetrics"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "timestamp" timestamp with time zone NOT NULL,
    wishlist_count integer NOT NULL,
    twitch_viewer_avg integer,
    youtube_trailer_views bigint,
    reddit_mentions integer NOT NULL,
    game_id integer NOT NULL,
    CONSTRAINT "PreRelelaseMetric_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."Predictions"
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    predicted_metacritic numeric(4, 1) NOT NULL,
    sales_class character varying(50) COLLATE pg_catalog."default" NOT NULL,
    confidence numeric(3, 2) NOT NULL,
    risk_level character varying(20) COLLATE pg_catalog."default" NOT NULL,
    arguments text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL,
    verified boolean,
    game_id integer NOT NULL,
    CONSTRAINT "Prediction_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."Game"
    ADD CONSTRAINT "Game_developer_id_fkey" FOREIGN KEY (developer_id)
    REFERENCES public."Developers" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."NewsSentiment"
    ADD CONSTRAINT "NewsSentiment_game_id_fkey" FOREIGN KEY (game_id)
    REFERENCES public."Game" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."PreReleaseMetrics"
    ADD CONSTRAINT "PreRelelaseMetric_game_id_fkey" FOREIGN KEY (game_id)
    REFERENCES public."Game" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."Predictions"
    ADD CONSTRAINT "Prediction_game_id_fkey" FOREIGN KEY (game_id)
    REFERENCES public."Game" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;
